name: Bug Report
description: Report a bug in the Heavy Duty Platform

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which @heavy-duty/* package(s) are the source of the bug?
      options:
        - bulldozer
        - ngx-solana
        - ngx-websocket
        - rx-solana
        - rxjs
        - wallet-adapter
        - Don't known / other
      multiple: true
    validations:
      required: true

  - type: dropdown
    id: is-regression
    attributes:
      label: Is this a regression?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Please provide a link to a minimal reproduction of the bug

  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you saw
      render: true

  - type: textarea
    id: environment
    attributes:
      label: Please provide the environment you discovered this bug in 
      render: true
      placeholder: |
        Solana: 1.9.15 
        Anchor: 0.21.0
        Node: 14.17.0
        Package Manager: yarn 1.22.10
        OS: linux x64
  
  - type: textarea
    id: other
    attributes:
      label: Anything else?